export interface Card {
  id: string;
  setId: string;
  name: string;
  manaCost: string;
  cmc: number;
  types: string;
  text: string;
  toughness: string;
  power: string;
  rarity: string;
  foil: boolean;
  fullArt: boolean;
  textLess: boolean;
  cardMarketPrice: string;
  standard: string;
  pioneer: string;
  explorer: string;
  modern: string;
  legacy: string;
  pauper: string;
  vintage: string;
  commander: string;
  brawl: string;
  pauperCommander: string;
  duel: string;
  oldSchool: string;
  imageSizeNormal: string;
  imageSizeArtCrop: string;
  isDoubleCard: boolean | null;
  // doubleCards: any[];
}
